### ISSUE TITLE
Valid timeout in config logs an error

### ISSUE THREAD

**Issue by ildanno** [flagship-io/flagship-php-sdk#55]
When setting a valid value for timeout (both numeric and positive) an error is logged

### How to reproduce
Declare `\Flagship\Config\FlagshipConfig::decisionApi()->setTimeout(1000)` when configuring client

### Expected behaviour
Nothing happens

### Actual behaviour
An error is fired

**Comment by ildanno** [comment]
Sorry, I accidentally closed this issue while merging on my fork.

**Comment by Heihokon** [comment]
Hi @ildanno, this issue has been fixed in version [3.1.2](https://packagist.org/packages/flagship-io/flagship-php-sdk#3.1.2)

Thanks so much for your contribution !
